services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8081:80
    volumes:
      - "./sources/php:/app"
    networks:
      - modulo

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - "./sources/php:/app"
    networks:
      - modulo

  db:
    image: mariadb:10.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modulo
      MYSQL_USER: modulo
      MYSQL_PASSWORD: modulo
    networks:
      - modulo

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    stdin_open: true
    environment:
      - "CI=true"
    volumes:
      - "$PWD/sources/node:/app"
    ports:
      - 3000:3000
    networks:
      - modulo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
        PMA_HOST: db
    depends_on:
      - db
    networks:
      - modulo

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1000:80
    networks:
      - modulo

networks:
  modulo:
    driver: bridge
